// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gh_encode
CharacterVector gh_encode(NumericVector lats, NumericVector lngs, IntegerVector precision);
RcppExport SEXP geohash_gh_encode(SEXP latsSEXP, SEXP lngsSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lngs(lngsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(gh_encode(lats, lngs, precision));
    return rcpp_result_gen;
END_RCPP
}
// gh_decode
DataFrame gh_decode(CharacterVector hashes);
RcppExport SEXP geohash_gh_decode(SEXP hashesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type hashes(hashesSEXP);
    rcpp_result_gen = Rcpp::wrap(gh_decode(hashes));
    return rcpp_result_gen;
END_RCPP
}
// gh_neighbours
DataFrame gh_neighbours(CharacterVector hashes);
RcppExport SEXP geohash_gh_neighbours(SEXP hashesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type hashes(hashesSEXP);
    rcpp_result_gen = Rcpp::wrap(gh_neighbours(hashes));
    return rcpp_result_gen;
END_RCPP
}
// gh_neighbour
CharacterVector gh_neighbour(CharacterVector hashes, IntegerVector direction);
RcppExport SEXP geohash_gh_neighbour(SEXP hashesSEXP, SEXP directionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type hashes(hashesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type direction(directionSEXP);
    rcpp_result_gen = Rcpp::wrap(gh_neighbour(hashes, direction));
    return rcpp_result_gen;
END_RCPP
}
